### ISSUE TITLE
Breaks Emoji

### ISSUE THREAD

**Issue by scyt** [pdeljanov/infinality-remix#11]
No emoji fonts will display after installing. I have Noto Color Emoji installed, and use [this fontconfig](https://github.com/stove-panini/fontconfig-emoji) to display it, but switching to infinality-remix has caused all emoji to display as blank. `fc-match` for any emoji returns Roboto instead.

**Comment by pdeljanov** [comment]
I don't think you need the linked instructions, I managed to fix it by adjusting some fontconfig symlinks. Do the changes below work for you?
```
cd /etc/fonts/conf.d
sudo ln -s ../conf.avail/45-generic.conf 45-generic.conf
sudo ln -s ../conf.avail/60-generic.conf 60-generic.conf
sudo rm 82-no-embedded-bitmaps.conf
fc-cache -rf
```

After doing this `fc-match emoji` should return an Emoji font. I have `extra/noto-fonts-emoji` installed so it returns Noto Color Emoji.

**Comment by scyt** [comment]
Those changes fix it, thank you! I also needed this symlink for bitmap scaling:

`sudo ln -s ../conf.avail/10-scale-bitmap-fonts.conf 10-scale-bitmap-fonts.conf`

**Comment by pdeljanov** [comment]
Thanks for the confirmation. Was wondering if that was needed, but it seemed to work fine without it. Good to know!

**Comment by donihalim** [comment]
Fixed my issue too, Thank you.
