### ISSUE TITLE
freetype2-infinality-remix won't build

### ISSUE THREAD

**Issue by Vixtron** [pdeljanov/infinality-remix#14]
Recently, `freetype2` was updated to `20.10.3` in the Arch [Repos](https://www.archlinux.org/packages/extra/x86_64/freetype2/) 
`freetype2-infinality-remix` patches broke, it won't build the package ever since the update.

**Comment by pdeljanov** [comment]
I've ported the patches to freetype2 version 2.10.4 in the freetype-2.10.4 branch, but unfortunately it crashes at runtime.

Closing this issue since #15 supersedes it.
