### ISSUE TITLE
Cant build with makepkg 

### ISSUE THREAD

**Issue by bradc87** [pdeljanov/infinality-remix#18]
<pre><code>
/home/brad/Downloads/freetype2-infinality-remix/src/freetype2-demos/src/ftdump.c:20:10: error: #include expects "FILENAME" or <FILENAME>
   20 | #include FT_INTERNAL_DEBUG_H
      |          ^~~~~~~~~~~~~~~~~~~
/home/brad/Downloads/freetype2-infinality-remix/src/freetype2-demos/src/ftdump.c:24:10: error: #include expects "FILENAME" or <FILENAME>
   24 | #include FT_INTERNAL_OBJECTS_H
      |          ^~~~~~~~~~~~~~~~~~~~~
/home/brad/Downloads/freetype2-infinality-remix/src/freetype2-demos/src/ftdump.c:25:10: error: #include expects "FILENAME" or <FILENAME>
   25 | #include FT_INTERNAL_DRIVER_H
      |          ^~~~~~~~~~~~~~~~~~~~
/home/brad/Downloads/freetype2-infinality-remix/src/freetype2-demos/src/ftdump.c: In function ‘Print_Type’:
/home/brad/Downloads/freetype2-infinality-remix/src/freetype2-demos/src/ftdump.c:162:27: error: invalid use of undefined type ‘struct FT_DriverRec_’
  162 |     module = &face->driver->root;
      |                           ^~
/home/brad/Downloads/freetype2-infinality-remix/src/freetype2-demos/src/ftdump.c:163:47: error: invalid use of undefined type ‘struct FT_ModuleRec_’
  163 |     printf( "   FreeType driver: %s\n", module->clazz->module_name );
      |                                               ^~
make: *** [Makefile:405: /home/brad/Downloads/freetype2-infinality-remix/src/freetype2-demos/objs/ftdump.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

</code></pre>

**Comment by pdeljanov** [comment]
Does this occur if you just install `freetype2-infinality-remix` and not `freetype2-demos-infinality-remix`?

If that works, then install `freetype2-infinality-remix` first, and then the demos.

**Comment by mokulus** [comment]
I have the same problem. Just doing ```yay -S freetype2-infinality-remix``` gives this error.

**Comment by ajP89** [comment]
how to install them separately?

**Comment by pdeljanov** [comment]
Okay, I think the problem occurs because freetype2-infinality-remix and freetype2-demos-infinality-remix are being built in a split package. When compiling the demos, it picks up the system freetype2 headers, which are version 2.10.4 if the official package is installed. There appear to be breaking changes between 2.10.4 and 2.10.1, thus the build error.

I think the only way forward is to split the PKGBUILD into 2 different packages, or just drop the demos all together.

The following diff to the PKGBUILD is a minimal workaround for now. Will implement a proper solution in the next few days.

```diff
--- a/freetype2-infinality-remix/PKGBUILD
+++ b/freetype2-infinality-remix/PKGBUILD
@@ -2,7 +2,7 @@
 # Contributor: bohoomil <bohoomil at zoho dot com>
 
 pkgbase=freetype2-infinality-remix
-pkgname=(freetype2-infinality-remix freetype2-demos-infinality-remix)
+pkgname=freetype2-infinality-remix
 pkgver=2.10.1
 pkgrel=1
 _patchrel=2019.08.21
@@ -73,8 +73,8 @@ build() {
     make
 
     # Build FreeType demos
-    cd ../freetype2-demos
-    make
+#     cd ../freetype2-demos
+#     make
 }
```

**Comment by pdeljanov** [comment]
Version 2.10.1-2 in the AUR should fix this now.

**Comment by ajP89** [comment]
thanks..works perfectly now
