### ISSUE TITLE
Fontconfig build fails while generating fontconfig-user.pdf

### ISSUE THREAD

**Issue by skylize** [pdeljanov/infinality-remix#19]
Package `fontconfig-infinality-remix` fails to build after receiving an error code from pdfTex. Same occurs running `makepkg -sci` on github repo. (I can't install the package just because the docs are mangled. :rofl: )

```
# ...

LaTeX Font Warning: Size substitutions with differences
(Font)              up to 0.44003pt have occurred.

 )
(see the transcript file for additional information){/usr/share/texmf-dist/font
s/enc/dvips/base/8r.enc}</usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/c
mmi10.pfb></usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi9.pfb></usr
/share/texmf-dist/fonts/type1/urw/courier/ucrb8a.pfb></usr/share/texmf-dist/fon
ts/type1/urw/courier/ucrr8a.pfb></usr/share/texmf-dist/fonts/type1/urw/helvetic
/uhvb8a.pfb></usr/share/texmf-dist/fonts/type1/urw/times/utmr8a.pfb></usr/share
/texmf-dist/fonts/type1/urw/times/utmri8a.pfb>
Output written on fontconfig-user.pdf (18 pages, 121969 bytes).
Transcript written on fontconfig-user.log.
make[3]: *** [Makefile:1351: fontconfig-user.pdf] Error 9
make[3]: *** Waiting for unfinished jobs....
Done.
Done.
Done.
make[3]: Leaving directory '/home/sky/.cache/yay/fontconfig-infinality-remix/src/fontconfig/doc'
make[2]: *** [Makefile:758: all] Error 2

# ...
```

The referenced log file shows
```
# ...

[12.0.36]
Overfull \hbox (42.55472pt too wide) in paragraph at lines 4129--4129
 [] $\OML/cmm/m/it/9 <$\T1/pcr/m/n/9 test qual="all" name="family" compare="not
_eq"$\OML/cmm/m/it/9 >$$<$\T1/pcr/m/n/9 string$\OML/cmm/m/it/9 >$\T1/pcr/m/n/9 
sans-serif$\OML/cmm/m/it/9 <$\T1/pcr/m/n/9 /string$\OML/cmm/m/it/9 >$$<$\T1/pcr
/m/n/9 /test$\OML/cmm/m/it/9 >$[] 
 []

# ... 
# and several more like that one 
# ...

[15.0.36] [16.0.36]
! Undefined control sequence.
<recently read> \Hy@colorlink 
                              
l.4680 {DEBUG}}
               Debugging Applications\endLink{}\endNode{} section for more d...
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

# ... 
# and several more like that one 

[17.0.36] [18.0.36]
(/home/sky/.cache/yay/fontconfig-infinality-remix/src/fontconfig/doc/fontconfig
-user.aux)

LaTeX Font Warning: Size substitutions with differences
(Font)              up to 0.44003pt have occurred.

# ... misc stats, before presumably exiting with an error code
```

**Comment by ajP89** [comment]
from https://aur.archlinux.org/packages/fontconfig-infinality-remix/:

gaougalos commented on 2020-12-08 10:10	

i get this error
make[3]: *** [Makefile:1351: fontconfig-user.pdf] Error 9
when i try to build this package

so i build it with
--disable-docs
and everything works

**Comment by nero-0** [comment]
@ajP89 Where do I put this? I am getting this pdf error.

**Comment by ajP89** [comment]
i'm not sure....try makepkg -sci --disable-docs. I myself downlaoded from AUR and it installed without issues.

**Comment by nero-0** [comment]
Yea, I tried, it doesn't work. Weird... it seems to happen with only a few people.

**Comment by pdeljanov** [comment]
That's.. interesting. I compiled and installed it no problem a while ago, but I can't build it now. Perhaps something within a latex package has changed...

**Comment by nero-0** [comment]
Good to know... I hope you find the problem wherever it is.

**Comment by skylize** [comment]
Glad its reproducable. Any vague estimate on when you might get to fixing this? Suggestions on a workaround in the meantime?

**Comment by pdeljanov** [comment]
Should be fixed now. The official Arch PKGBUILD is also broken in the same way, so I disabled docs for now. Once the official Arch package updates hopefully we can re-enable them. The `fontconfig-docs` package can be installed if anyone needs the documentation.

**Comment by skylize** [comment]
Thanks. Confirmed, building correctly on my system. Definitely think docs are pretty secondary to the goals of the package. Strongly support the decision to simply remove them from the build to keep installation working. 👍🏼
