### ISSUE TITLE
Use Times New Roman font

### ISSUE THREAD

**Issue by ColemanGariety** [pdeljanov/infinality-remix#20]
I have the `Times New Roman` font on my system, but due to `infinality-remix` it always loads the `Liberation Serif` font instead. Is this the expected behavior? I must prefer the `Times New Roman` font.

**Comment by pdeljanov** [comment]
This is intended behaviour. The `fontconfig-infinality-remix` package is mainly a set of font substitutions with 4 presets that can be changed with the `fc-presets` command.

If you don't want any substitutions, you can simply remove the current preset using `fc-presets` or better, just install the official `fontconfig` package. As long as you followed steps 4-6 in the README, your fonts will be rendered just as well.

**Comment by ColemanGariety** [comment]
Okay thanks!
