### ISSUE TITLE
As install this pkg will break the dependencies of other pkgs, is there some demo effect comparation?

### ISSUE THREAD

**Issue by faywong** [pdeljanov/infinality-remix#5]

**Comment by pdeljanov** [comment]
These packages will not break any dependent packages. They provide drop-in alternatives to the official `freetype`, `cairo`, and `fontconfig` packages and track upstream. It's a very simple and easy install process if you have a typical Arch system.

I don't have any comparisons at the moment, but I uploaded some [sample screenshots](https://github.com/pdeljanov/infinality-remix/tree/master/samples) to the repository.

**Comment by faywong** [comment]
I mean replace the ``freetype`` package would really break the dependency of some packages(for me this is the case), so i need to think twice and evaluate the risk before going on. Anyway i will paste the conplain of pacman here later.

>>I don't have any comparisons at the moment, but I uploaded some sample screenshots to the repository.
If i tried success, i would like to contribute the effect comparation here. Anyway, thank you for your great job.
