### ISSUE TITLE
infinality-remix for Fedora 30/31?

### ISSUE THREAD

**Issue by fastrizwaan** [pdeljanov/infinality-remix#9]
Could you provide build instructions, please!?

**Comment by pdeljanov** [comment]
Sorry, these packages are for Arch Linux only. I have no experience with packaging on Fedora.

If you want to build the libraries manually, you can use the `PKGBUILD` files in the `cairo-infinality-remix`,`fontconfig-infinality-remix`, `freetype2-infinality-remix` folders as a guide. Generally you'll just need to apply the patches to the upstream packages and then do the regular build procedure (configure + make).

**Comment by fastrizwaan** [comment]
well, dawid/better_fonts https://github.com/silenc3r/fedora-better-fonts really make difference in Fedora 30/31 without infinality patches. Here's a screenshot fedora 31 with better fonts without freetype infinality patches. Just sharing this info for other Fedora users and for non-infinality users.Thanks.

![Archlinux Wikipedia with better fonts on fedora on 2020-01-08 21-16-48](https://user-images.githubusercontent.com/1161682/71993719-95839f80-325d-11ea-9d69-d72d45da2a39.png)
